In [ ]:
#Import necessary libraries and data paths

import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

RAW_PATH = Path("../dataset/raw/flights_sample_3m.csv")
PROCESSED_DIR = Path("../dataset/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [ ]:

#load the raw data

df = pd.read_csv(RAW_PATH, low_memory=False)

print("Raw shape:", df.shape)
display(df.head())
display(df.info())

Raw shape: (3000000, 32)

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,1501,1447.0,-14.0,0.0,NaN,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0.0,NaN,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0.0,NaN,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,1829,1853.0,24.0,0.0,NaN,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,2041,2040.0,-1.0,0.0,NaN,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 32 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  object
 1   AIRLINE                  object
 2   AIRLINE_DOT              object
 3   AIRLINE_CODE             object
 4   DOT_CODE                 int64
 5   FL_NUMBER                int64
 6   ORIGIN                   object
 7   ORIGIN_CITY              object
 8   DEST                     object
 9   DEST_CITY                object
 10  CRS_DEP_TIME             int64
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int64
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        object
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
dtypes: float64(19), int64(4), object(9)
memory usage: 732.4+ MB

None

In [ ]:
# Clean column names: strip whitespace, convert to uppercase, replace spaces with underscores
df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace(" ", "_")
)

print(df.columns)

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE',
       'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='object')

In [ ]:
# Select only the columns we need for analysis and visualization
cols_to_keep = [
    "FL_DATE",
    "AIRLINE",
    "AIRLINE_CODE",
    "FL_NUMBER",

    "ORIGIN",
    "ORIGIN_CITY",
    "DEST",
    "DEST_CITY",

    "CRS_DEP_TIME",
    "DEP_TIME",
    "DEP_DELAY",
    "TAXI_OUT",
    "WHEELS_OFF",

    "WHEELS_ON",
    "TAXI_IN",
    "CRS_ARR_TIME",
    "ARR_TIME",
    "ARR_DELAY",

    "CANCELLED",
    "CANCELLATION_CODE",
    "DIVERTED",

    "CRS_ELAPSED_TIME",
    "ELAPSED_TIME",
    "AIR_TIME",
    "DISTANCE",

    "DELAY_DUE_CARRIER",
    "DELAY_DUE_WEATHER",
    "DELAY_DUE_NAS",
    "DELAY_DUE_SECURITY",
    "DELAY_DUE_LATE_AIRCRAFT"
]

existing_cols = [col for col in cols_to_keep if col in df.columns]
missing_cols = [col for col in cols_to_keep if col not in df.columns]

df = df[existing_cols].copy()

print("Kept columns:", len(existing_cols))
print("Missing columns:", missing_cols)
print("Shape after selection:", df.shape)
display(df.head())

Kept columns: 30
Missing columns: []
Shape after selection: (3000000, 30)

,FL_DATE,AIRLINE,AIRLINE_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,UA,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,1501,1447.0,-14.0,0.0,NaN,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,DL,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0.0,NaN,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,UA,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0.0,NaN,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,DL,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,1829,1853.0,24.0,0.0,NaN,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,NK,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,2041,2040.0,-1.0,0.0,NaN,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
print("Rows before date cleaning:", df.shape[0])
print("Sample dates:")
display(df["FL_DATE"].head())

df["FL_DATE"] = pd.to_datetime(df["FL_DATE"], errors="coerce") #convert to datetime, invalid parsing will be set as NaT
 
print("Invalid dates:", df["FL_DATE"].isna().sum())

df = df.dropna(subset=["FL_DATE"]).copy() #drop rows where date is invalid (NaT)

df["YEAR"] = df["FL_DATE"].dt.year
df["MONTH"] = df["FL_DATE"].dt.month
df["MONTH_NAME"] = df["FL_DATE"].dt.month_name()
df["DAY"] = df["FL_DATE"].dt.day
df["DAY_OF_WEEK"] = df["FL_DATE"].dt.dayofweek + 1
df["DAY_NAME"] = df["FL_DATE"].dt.day_name()
df["QUARTER"] = df["FL_DATE"].dt.quarter

print("Rows after date cleaning:", df.shape[0])
print("Date range:", df["FL_DATE"].min(), "to", df["FL_DATE"].max())
display(df["YEAR"].value_counts().sort_index())

Rows before date cleaning: 3000000
Sample dates:

0    2019-01-09
1    2022-11-19
2    2022-07-22
3    2023-03-06
4    2020-02-23
Name: FL_DATE, dtype: object

Invalid dates: 0
Rows after date cleaning: 3000000
Date range: 2019-01-01 00:00:00 to 2023-08-31 00:00:00

YEAR
2019    757673
2020    479350
2021    611633
2022    687860
2023    463484
Name: count, dtype: int64

In [ ]:
# Convert numeric columns to appropriate types, coercing errors to NaN
numeric_cols = [
    "FL_NUMBER",
    "CRS_DEP_TIME",
    "DEP_TIME",
    "DEP_DELAY",
    "TAXI_OUT",
    "WHEELS_OFF",
    "WHEELS_ON",
    "TAXI_IN",
    "CRS_ARR_TIME",
    "ARR_TIME",
    "ARR_DELAY",
    "CANCELLED",
    "DIVERTED",
    "CRS_ELAPSED_TIME",
    "ELAPSED_TIME",
    "AIR_TIME",
    "DISTANCE",
    "DELAY_DUE_CARRIER",
    "DELAY_DUE_WEATHER",
    "DELAY_DUE_NAS",
    "DELAY_DUE_SECURITY",
    "DELAY_DUE_LATE_AIRCRAFT",
    "YEAR",
    "MONTH",
    "DAY",
    "DAY_OF_WEEK",
    "QUARTER"
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

categorical_cols = [
    "AIRLINE",
    "AIRLINE_CODE",
    "ORIGIN",
    "ORIGIN_CITY",
    "DEST",
    "DEST_CITY",
    "CANCELLATION_CODE",
    "MONTH_NAME",
    "DAY_NAME"
]
# Convert categorical columns to string type
for col in categorical_cols:
    if col in df.columns:
        df[col] = df[col].astype("string")

In [ ]:

delay_cause_cols = [
    "DELAY_DUE_CARRIER",
    "DELAY_DUE_WEATHER",
    "DELAY_DUE_NAS",
    "DELAY_DUE_SECURITY",
    "DELAY_DUE_LATE_AIRCRAFT"
]

# Delay causes are blank when no delay reason was recorded.
df[delay_cause_cols] = df[delay_cause_cols].fillna(0)

# status columns: fill missing with 0 (not cancelled/diverted) and convert to int
df["CANCELLED"] = df["CANCELLED"].fillna(0).astype(int)
df["DIVERTED"] = df["DIVERTED"].fillna(0).astype(int)

# Cancellation code exists only for cancelled flights.
df["CANCELLATION_CODE"] = df["CANCELLATION_CODE"].fillna("Not cancelled")

In [ ]:

print("Missing values before operational cleaning:")
display(df.isna().sum().sort_values(ascending=False).head(20))

# Keep cancelled flights for cancellation analysis.
cancelled_df = df[df["CANCELLED"] == 1].copy()
non_cancelled_df = df[df["CANCELLED"] == 0].copy()

required_operational_cols = [
    "DEP_DELAY",
    "ARR_DELAY",
    "TAXI_OUT",
    "TAXI_IN",
    "ELAPSED_TIME",
    "AIR_TIME"
]

non_cancelled_df = non_cancelled_df.dropna(subset=required_operational_cols)

df = pd.concat([non_cancelled_df, cancelled_df], ignore_index=True)

# For cancelled flights, operational values are structurally missing.
operational_fill_zero = [
    "DEP_TIME",
    "DEP_DELAY",
    "TAXI_OUT",
    "WHEELS_OFF",
    "WHEELS_ON",
    "TAXI_IN",
    "ARR_TIME",
    "ARR_DELAY",
    "ELAPSED_TIME",
    "AIR_TIME"
]

df[operational_fill_zero] = df[operational_fill_zero].fillna(0)

print("Shape after operational cleaning:", df.shape)

print("Missing values after operational cleaning:")
display(df.isna().sum().sort_values(ascending=False).head(20))

Missing values before operational cleaning:

AIR_TIME                   86198
ELAPSED_TIME               86198
ARR_DELAY                  86198
TAXI_IN                    79944
WHEELS_ON                  79944
ARR_TIME                   79942
TAXI_OUT                   78806
WHEELS_OFF                 78806
DEP_DELAY                  77644
DEP_TIME                   77615
CRS_ELAPSED_TIME              14
DELAY_DUE_LATE_AIRCRAFT        0
YEAR                           0
DISTANCE                       0
MONTH                          0
MONTH_NAME                     0
DELAY_DUE_SECURITY             0
DAY                            0
DAY_OF_WEEK                    0
DELAY_DUE_NAS                  0
dtype: int64

Shape after operational cleaning: (2992942, 37)
Missing values after operational cleaning:

CRS_ELAPSED_TIME           14
FL_DATE                     0
CANCELLATION_CODE           0
ELAPSED_TIME                0
AIR_TIME                    0
DISTANCE                    0
DELAY_DUE_CARRIER           0
DELAY_DUE_WEATHER           0
DELAY_DUE_NAS               0
DELAY_DUE_SECURITY          0
DELAY_DUE_LATE_AIRCRAFT     0
YEAR                        0
MONTH                       0
MONTH_NAME                  0
DAY                         0
DAY_OF_WEEK                 0
DAY_NAME                    0
DIVERTED                    0
CANCELLED                   0
AIRLINE                     0
dtype: int64

In [ ]:
# Create new features for analysis and visualization

df["ROUTE"] = df["ORIGIN"] + " → " + df["DEST"]

df["DEP_DELAY_MINUTES"] = df["DEP_DELAY"].clip(lower=0) #negative delays (early departures) are set to 0 for delay analysis
df["ARR_DELAY_MINUTES"] = df["ARR_DELAY"].clip(lower=0) #negative delays (early arrivals) are set to 0 for delay analysis

df["IS_DELAYED"] = (df["ARR_DELAY"] >= 15).astype(int) #flights with arrival delay of 15 minutes or more are considered delayed
df["IS_DEP_DELAYED"] = (df["DEP_DELAY"] >= 15).astype(int) #flights with departure delay of 15 minutes or more are considered departure delayed
df["IS_CANCELLED"] = (df["CANCELLED"] == 1).astype(int) #flights with CANCELLED=1 are marked as cancelled
df["IS_DIVERTED"] = (df["DIVERTED"] == 1).astype(int)# flights with DIVERTED=1 are marked as diverted
def season_from_month(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"

df["SEASON"] = df["MONTH"].apply(season_from_month)
# Define delay severity based on arrival delay minutes
def delay_severity(minutes):
    if minutes <= 0:
        return "On time / Early"
    elif minutes < 15:
        return "Minor delay"
    elif minutes < 60:
        return "Moderate delay"
    else:
        return "Severe delay"

df["DELAY_SEVERITY"] = df["ARR_DELAY_MINUTES"].apply(delay_severity)
# Create a total delay cause column by summing all individual causes
df["TOTAL_DELAY_CAUSE"] = df[delay_cause_cols].sum(axis=1)

def dominant_delay_cause(row):
    causes = {
        "Carrier": row["DELAY_DUE_CARRIER"],
        "Weather": row["DELAY_DUE_WEATHER"],
        "NAS": row["DELAY_DUE_NAS"],
        "Security": row["DELAY_DUE_SECURITY"],
        "Late Aircraft": row["DELAY_DUE_LATE_AIRCRAFT"]
    }

    if sum(causes.values()) == 0:
        return "No recorded cause"

    return max(causes, key=causes.get)

df["DOMINANT_DELAY_CAUSE"] = df.apply(dominant_delay_cause, axis=1)

cancel_map = {
    "A": "Carrier",
    "B": "Weather",
    "C": "National Air System",
    "D": "Security",
    "Not cancelled": "Not cancelled"
}
# Map cancellation codes to reasons, with a default for non-cancelled flights
df["CANCELLATION_REASON"] = df["CANCELLATION_CODE"].map(cancel_map).fillna("Not cancelled")

def punctuality_status(row):
    if row["CANCELLED"] == 1:
        return "Cancelled"
    elif row["DIVERTED"] == 1:
        return "Diverted"
    elif row["ARR_DELAY"] >= 15:
        return "Delayed"
    else:
        return "On time"

df["PUNCTUALITY_STATUS"] = df.apply(punctuality_status, axis=1)

display(df.head())

,FL_DATE,AIRLINE,AIRLINE_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT,YEAR,MONTH,MONTH_NAME,DAY,DAY_OF_WEEK,DAY_NAME,QUARTER,ROUTE,DEP_DELAY_MINUTES,ARR_DELAY_MINUTES,IS_DELAYED,IS_DEP_DELAYED,IS_CANCELLED,IS_DIVERTED,SEASON,DELAY_SEVERITY,TOTAL_DELAY_CAUSE,DOMINANT_DELAY_CAUSE,CANCELLATION_REASON,PUNCTUALITY_STATUS
0,2019-01-09,United Air Lines Inc.,UA,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,1501,1447.0,-14.0,0,Not cancelled,0,186.0,176.0,153.0,1065.0,0.0,0.0,0.0,0.0,0.0,2019,1,January,9,3,Wednesday,1,FLL → EWR,0.0,0.0,0,0,0,0,Winter,On time / Early,0.0,No recorded cause,Not cancelled,On time
1,2022-11-19,Delta Air Lines Inc.,DL,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0,Not cancelled,0,235.0,236.0,189.0,1399.0,0.0,0.0,0.0,0.0,0.0,2022,11,November,19,6,Saturday,4,MSP → SEA,0.0,0.0,0,0,0,0,Autumn,On time / Early,0.0,No recorded cause,Not cancelled,On time
2,2022-07-22,United Air Lines Inc.,UA,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0,Not cancelled,0,118.0,112.0,87.0,680.0,0.0,0.0,0.0,0.0,0.0,2022,7,July,22,5,Friday,3,DEN → MSP,6.0,0.0,0,0,0,0,Summer,On time / Early,0.0,No recorded cause,Not cancelled,On time
3,2023-03-06,Delta Air Lines Inc.,DL,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,1829,1853.0,24.0,0,Not cancelled,0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0,2023,3,March,6,1,Monday,1,MSP → SFO,0.0,24.0,1,0,0,0,Spring,Moderate delay,24.0,NAS,Not cancelled,Delayed
4,2020-02-23,Spirit Air Lines,NK,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,2041,2040.0,-1.0,0,Not cancelled,0,181.0,182.0,153.0,985.0,0.0,0.0,0.0,0.0,0.0,2020,2,February,23,7,Sunday,1,MCO → DFW,0.0,0.0,0,0,0,0,Winter,On time / Early,0.0,No recorded cause,Not cancelled,On time

In [ ]:
# Convert categorical columns to category dtype for memory efficiency
category_cols = [
    "AIRLINE",
    "AIRLINE_CODE",
    "ORIGIN",
    "ORIGIN_CITY",
    "DEST",
    "DEST_CITY",
    "CANCELLATION_CODE",
    "MONTH_NAME",
    "DAY_NAME",
    "ROUTE",
    "SEASON",
    "DELAY_SEVERITY",
    "DOMINANT_DELAY_CAUSE",
    "CANCELLATION_REASON",
    "PUNCTUALITY_STATUS"
]

for col in category_cols:
    if col in df.columns:
        df[col] = df[col].astype("category")

print(df.info(memory_usage="deep"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2992942 entries, 0 to 2992941
Data columns (total 50 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  datetime64[ns]
 1   AIRLINE                  category
 2   AIRLINE_CODE             category
 3   FL_NUMBER                int64
 4   ORIGIN                   category
 5   ORIGIN_CITY              category
 6   DEST                     category
 7   DEST_CITY                category
 8   CRS_DEP_TIME             int64
 9   DEP_TIME                 float64
 10  DEP_DELAY                float64
 11  TAXI_OUT                 float64
 12  WHEELS_OFF               float64
 13  WHEELS_ON                float64
 14  TAXI_IN                  float64
 15  CRS_ARR_TIME             int64
 16  ARR_TIME                 float64
 17  ARR_DELAY                float64
 18  CANCELLED                int32
 19  CANCELLATION_CODE        category
 20  DIVERTED                 int32
 21  CRS_ELAPSED_TIME         float64
 22  ELAPSED_TIME             float64
 23  AIR_TIME                 float64
 24  DISTANCE                 float64
 25  DELAY_DUE_CARRIER        float64
 26  DELAY_DUE_WEATHER        float64
 27  DELAY_DUE_NAS            float64
 28  DELAY_DUE_SECURITY       float64
 29  DELAY_DUE_LATE_AIRCRAFT  float64
 30  YEAR                     int32
 31  MONTH                    int32
 32  MONTH_NAME               category
 33  DAY                      int32
 34  DAY_OF_WEEK              int32
 35  DAY_NAME                 category
 36  QUARTER                  int32
 37  ROUTE                    category
 38  DEP_DELAY_MINUTES        float64
 39  ARR_DELAY_MINUTES        float64
 40  IS_DELAYED               int32
 41  IS_DEP_DELAYED           int32
 42  IS_CANCELLED             int32
 43  IS_DIVERTED              int32
 44  SEASON                   category
 45  DELAY_SEVERITY           category
 46  TOTAL_DELAY_CAUSE        float64
 47  DOMINANT_DELAY_CAUSE     category
 48  CANCELLATION_REASON      category
 49  PUNCTUALITY_STATUS       category
dtypes: category(15), datetime64[ns](1), float64(20), int32(11), int64(3)
memory usage: 731.9 MB
None

In [ ]:
# Create summary tables for Shiny app
airline_summary = (
    df.groupby(["AIRLINE_CODE", "AIRLINE"], observed=True)
    .agg(
        total_flights=("FL_NUMBER", "count"),
        avg_dep_delay=("DEP_DELAY_MINUTES", "mean"),
        avg_arr_delay=("ARR_DELAY_MINUTES", "mean"),
        delay_rate=("IS_DELAYED", "mean"),
        cancellation_rate=("IS_CANCELLED", "mean"),
        diversion_rate=("IS_DIVERTED", "mean"),
        avg_distance=("DISTANCE", "mean"),
        avg_air_time=("AIR_TIME", "mean")
    )
    .reset_index()
)
# Summarize by origin airport and city
airport_summary = (
    df.groupby(["ORIGIN", "ORIGIN_CITY"], observed=True)
    .agg(
        total_departures=("FL_NUMBER", "count"),
        avg_dep_delay=("DEP_DELAY_MINUTES", "mean"),
        avg_arr_delay=("ARR_DELAY_MINUTES", "mean"),
        delay_rate=("IS_DELAYED", "mean"),
        cancellation_rate=("IS_CANCELLED", "mean"),
        avg_taxi_out=("TAXI_OUT", "mean")
    )
    .reset_index()
)
# Summarize by destination airport and city
route_summary = (
    df.groupby(["ORIGIN", "DEST", "ROUTE"], observed=True)
    .agg(
        total_flights=("FL_NUMBER", "count"),
        avg_dep_delay=("DEP_DELAY_MINUTES", "mean"),
        avg_arr_delay=("ARR_DELAY_MINUTES", "mean"),
        delay_rate=("IS_DELAYED", "mean"),
        cancellation_rate=("IS_CANCELLED", "mean"),
        avg_distance=("DISTANCE", "mean"),
        avg_air_time=("AIR_TIME", "mean")
    )
    .reset_index()
)

monthly_summary = (
    df.groupby(["YEAR", "MONTH", "MONTH_NAME"], observed=True)
    .agg(
        total_flights=("FL_NUMBER", "count"),
        avg_dep_delay=("DEP_DELAY_MINUTES", "mean"),
        avg_arr_delay=("ARR_DELAY_MINUTES", "mean"),
        delay_rate=("IS_DELAYED", "mean"),
        cancellation_rate=("IS_CANCELLED", "mean"),
        diversion_rate=("IS_DIVERTED", "mean")
    )
    .reset_index()
)

yearly_summary = (
    df.groupby("YEAR", observed=True)
    .agg(
        total_flights=("FL_NUMBER", "count"),
        avg_dep_delay=("DEP_DELAY_MINUTES", "mean"),
        avg_arr_delay=("ARR_DELAY_MINUTES", "mean"),
        delay_rate=("IS_DELAYED", "mean"),
        cancellation_rate=("IS_CANCELLED", "mean"),
        diversion_rate=("IS_DIVERTED", "mean")
    )
    .reset_index()
)

weekday_summary = (
    df.groupby(["DAY_OF_WEEK", "DAY_NAME"], observed=True)
    .agg(
        total_flights=("FL_NUMBER", "count"),
        avg_arr_delay=("ARR_DELAY_MINUTES", "mean"),
        delay_rate=("IS_DELAYED", "mean"),
        cancellation_rate=("IS_CANCELLED", "mean")
    )
    .reset_index()
)

delay_cause_summary = (
    df.groupby(["YEAR", "MONTH"], observed=True)[delay_cause_cols]
    .sum()
    .reset_index()
)

status_summary = (
    df.groupby("PUNCTUALITY_STATUS", observed=True)
    .agg(total_flights=("FL_NUMBER", "count"))
    .reset_index()
)

In [ ]:
# Basic quality checks on the cleaned dataset
print("Cleaned dataset shape:", df.shape)

print("\nDate range:")
print(df["FL_DATE"].min(), "to", df["FL_DATE"].max())

print("\nYear distribution:")
display(df["YEAR"].value_counts().sort_index())

print("\nMissing values:")
display(df.isna().sum().sort_values(ascending=False).head(20))

print("\nPunctuality status distribution:")
display(df["PUNCTUALITY_STATUS"].value_counts())

print("\nDelay severity distribution:")
display(df["DELAY_SEVERITY"].value_counts())

print("\nTop airlines:")
display(
    airline_summary
    .sort_values("total_flights", ascending=False)
    .head(10)
)

print("\nWorst routes with at least 500 flights:")
display(
    route_summary
    .query("total_flights >= 500")
    .sort_values("avg_arr_delay", ascending=False)
    .head(10)
)

Cleaned dataset shape: (2992942, 50)

Date range:
2019-01-01 00:00:00 to 2023-08-31 00:00:00

Year distribution:

YEAR
2019    755690
2020    478580
2021    610241
2022    686209
2023    462222
Name: count, dtype: int64

Missing values:

CRS_ELAPSED_TIME           14
FL_DATE                     0
ROUTE                       0
DELAY_DUE_SECURITY          0
DELAY_DUE_LATE_AIRCRAFT     0
YEAR                        0
MONTH                       0
MONTH_NAME                  0
DAY                         0
DAY_OF_WEEK                 0
DAY_NAME                    0
QUARTER                     0
DEP_DELAY_MINUTES           0
DELAY_DUE_WEATHER           0
ARR_DELAY_MINUTES           0
IS_DELAYED                  0
IS_DEP_DELAYED              0
IS_CANCELLED                0
IS_DIVERTED                 0
SEASON                      0
dtype: int64

Punctuality status distribution:

PUNCTUALITY_STATUS
On time      2379939
Delayed       533863
Cancelled      79140
Name: count, dtype: int64

Delay severity distribution:

DELAY_SEVERITY
On time / Early    2014795
Minor delay         444284
Moderate delay      355451
Severe delay        178412
Name: count, dtype: int64

Top airlines:

,AIRLINE_CODE,AIRLINE,total_flights,avg_dep_delay,avg_arr_delay,delay_rate,cancellation_rate,diversion_rate,avg_distance,avg_air_time
15,WN,Southwest Airlines Co.,575334,12.143049,10.581078,0.186457,0.033833,0.0,740.000289,99.333372
4,DL,Delta Air Lines Inc.,394457,10.745660,10.553931,0.141876,0.015165,0.0,928.789602,123.049686
1,AA,American Airlines Inc.,382125,15.303398,15.420601,0.193298,0.028543,0.0,989.012106,130.007778
12,OO,SkyWest Airlines Inc.,342731,13.128573,13.510704,0.155288,0.022598,0.0,495.734725,74.845179
14,UA,United Air Lines Inc.,253806,14.202844,14.182175,0.187383,0.021812,0.0,1173.648799,150.348510
17,YX,Republic Airline,142793,10.027711,11.210550,0.152879,0.032537,0.0,545.914506,82.179316
9,MQ,Envoy Air,120945,10.187118,11.437554,0.168721,0.030038,0.0,482.851966,73.113299
3,B6,JetBlue Airways,112486,21.642996,21.399463,0.262726,0.027017,0.0,1159.896618,151.833481
0,9E,Endeavor Air Inc.,112242,9.753452,10.184619,0.127617,0.021329,0.0,418.998512,65.326527
11,OH,PSA Airlines Inc.,106784,12.110091,12.588712,0.168153,0.030913,0.0,413.410239,65.336670

Worst routes with at least 500 flights:

,ORIGIN,DEST,ROUTE,total_flights,avg_dep_delay,avg_arr_delay,delay_rate,cancellation_rate,avg_distance,avg_air_time
3632,JFK,PBI,JFK → PBI,834,27.237410,26.219424,0.273381,0.032374,1028.0,141.276978
2688,FLL,JFK,FLL → JFK,1754,27.005131,26.161345,0.274800,0.025086,1069.0,137.179590
1887,DEN,JFK,DEN → JFK,557,25.763016,25.755835,0.258528,0.028725,1626.0,186.468582
4307,MCO,JFK,MCO → JFK,1968,25.330285,25.466972,0.269817,0.029472,944.0,122.001016
1801,DEN,ASE,DEN → ASE,994,24.632797,25.169014,0.268612,0.084507,125.0,26.105634
7041,SJU,EWR,SJU → EWR,945,23.597884,24.748148,0.314286,0.020106,1608.0,215.283598
6026,PNS,DFW,PNS → DFW,758,24.010554,24.577836,0.230871,0.048813,604.0,91.631926
2551,EWR,SJU,EWR → SJU,913,25.108434,24.537788,0.313253,0.019715,1608.0,198.328587
4287,MCO,EWR,MCO → EWR,2847,23.190727,24.426063,0.298209,0.032666,937.0,123.035476
4594,MIA,JFK,MIA → JFK,2219,24.342046,24.177557,0.250113,0.027039,1089.0,139.210005

In [ ]:
# Export cleaned dataset and summary tables to CSV for Shiny app
df.to_csv(PROCESSED_DIR / "flights_cleaned.csv", index=False)

airline_summary.to_csv(PROCESSED_DIR / "airline_summary.csv", index=False)
airport_summary.to_csv(PROCESSED_DIR / "airport_summary.csv", index=False)
route_summary.to_csv(PROCESSED_DIR / "route_summary.csv", index=False)
monthly_summary.to_csv(PROCESSED_DIR / "monthly_summary.csv", index=False)
yearly_summary.to_csv(PROCESSED_DIR / "yearly_summary.csv", index=False)
weekday_summary.to_csv(PROCESSED_DIR / "weekday_summary.csv", index=False)
delay_cause_summary.to_csv(PROCESSED_DIR / "delay_cause_summary.csv", index=False)
status_summary.to_csv(PROCESSED_DIR / "status_summary.csv", index=False)

print("CSV export complete.")
print("Files saved to:", PROCESSED_DIR)

CSV export complete.
Files saved to: ..\dataset\processed

In [ ]:
#test read-back of the cleaned dataset to ensure it was saved correctly

test_df = pd.read_csv(PROCESSED_DIR / "flights_cleaned.csv")

print("Read-back successful.")
print(test_df.shape)
display(test_df.head())

Read-back successful.
(2992942, 50)

,FL_DATE,AIRLINE,AIRLINE_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT,YEAR,MONTH,MONTH_NAME,DAY,DAY_OF_WEEK,DAY_NAME,QUARTER,ROUTE,DEP_DELAY_MINUTES,ARR_DELAY_MINUTES,IS_DELAYED,IS_DEP_DELAYED,IS_CANCELLED,IS_DIVERTED,SEASON,DELAY_SEVERITY,TOTAL_DELAY_CAUSE,DOMINANT_DELAY_CAUSE,CANCELLATION_REASON,PUNCTUALITY_STATUS
0,2019-01-09,United Air Lines Inc.,UA,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,1501,1447.0,-14.0,0,Not cancelled,0,186.0,176.0,153.0,1065.0,0.0,0.0,0.0,0.0,0.0,2019,1,January,9,3,Wednesday,1,FLL → EWR,0.0,0.0,0,0,0,0,Winter,On time / Early,0.0,No recorded cause,Not cancelled,On time
1,2022-11-19,Delta Air Lines Inc.,DL,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0,Not cancelled,0,235.0,236.0,189.0,1399.0,0.0,0.0,0.0,0.0,0.0,2022,11,November,19,6,Saturday,4,MSP → SEA,0.0,0.0,0,0,0,0,Autumn,On time / Early,0.0,No recorded cause,Not cancelled,On time
2,2022-07-22,United Air Lines Inc.,UA,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0,Not cancelled,0,118.0,112.0,87.0,680.0,0.0,0.0,0.0,0.0,0.0,2022,7,July,22,5,Friday,3,DEN → MSP,6.0,0.0,0,0,0,0,Summer,On time / Early,0.0,No recorded cause,Not cancelled,On time
3,2023-03-06,Delta Air Lines Inc.,DL,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,1829,1853.0,24.0,0,Not cancelled,0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0,2023,3,March,6,1,Monday,1,MSP → SFO,0.0,24.0,1,0,0,0,Spring,Moderate delay,24.0,NAS,Not cancelled,Delayed
4,2020-02-23,Spirit Air Lines,NK,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,2041,2040.0,-1.0,0,Not cancelled,0,181.0,182.0,153.0,985.0,0.0,0.0,0.0,0.0,0.0,2020,2,February,23,7,Sunday,1,MCO → DFW,0.0,0.0,0,0,0,0,Winter,On time / Early,0.0,No recorded cause,Not cancelled,On time

In [ ]:
#airport map summary with airport lookup data for mapping in Shiny app
AIRPORTS_PATH = Path("../dataset/raw/airports.csv")

airports_lookup = pd.read_csv(AIRPORTS_PATH)

airports_lookup = airports_lookup[
    [
        "iata_code",
        "name",
        "latitude_deg",
        "longitude_deg",
        "iso_country",
        "type"
    ]
].copy()

airports_lookup = airports_lookup.dropna(subset=["iata_code", "latitude_deg", "longitude_deg"])

# Keep US airports only, since our flight dataset is US domestic
airports_lookup = airports_lookup[airports_lookup["iso_country"] == "US"]

airports_lookup = airports_lookup.rename(
    columns={
        "iata_code": "ORIGIN",
        "name": "AIRPORT_NAME",
        "latitude_deg": "LATITUDE",
        "longitude_deg": "LONGITUDE",
        "type": "AIRPORT_TYPE"
    }
)

airport_map_summary = airport_summary.merge(
    airports_lookup,
    on="ORIGIN",
    how="left"
)

airport_map_summary = airport_map_summary.dropna(subset=["LATITUDE", "LONGITUDE"])

print("Airport map summary shape:", airport_map_summary.shape)
display(airport_map_summary.head())

Airport map summary shape: (372, 13)

,ORIGIN,ORIGIN_CITY,total_departures,avg_dep_delay,avg_arr_delay,delay_rate,cancellation_rate,avg_taxi_out,AIRPORT_NAME,LATITUDE,LONGITUDE,iso_country,AIRPORT_TYPE
0,ABE,"Allentown/Bethlehem/Easton, PA",2018,14.024777,13.964817,0.157582,0.025273,14.155104,Lehigh Valley International Airport,40.651773,-75.442797,US,medium_airport
1,ABI,"Abilene, TX",901,12.820200,14.148724,0.177580,0.029967,12.749168,Abilene Regional Airport,32.411301,-99.681900,US,medium_airport
2,ABQ,"Albuquerque, NM",9264,11.711464,11.541775,0.156412,0.025259,13.129210,Albuquerque International Sunport,35.039976,-106.608925,US,large_airport
3,ABR,"Aberdeen, SD",332,18.370482,18.689759,0.102410,0.012048,14.548193,Aberdeen Regional Airport,45.449100,-98.421799,US,medium_airport
4,ABY,"Albany, GA",435,7.335632,7.501149,0.089655,0.011494,12.940230,Southwest Georgia Regional Airport,31.532946,-84.196215,US,medium_airport

In [16]:
airport_map_summary.to_csv(PROCESSED_DIR / "airport_map_summary.csv", index=False)